- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: "Install Java-21, maven and docker"
    shell:
      cmd: |
        yum update && yum upgrade -y;
        yum install java-21-amazon-corretto -y;
        yum install maven -y;
        yum install docker -y;
    notify: "enable-start-docker"

  handlers:
  - name: "enable-start-docker"
    shell:
      cmd: |
        systemctl enable docker; systemctl start docker;